[project]
name = "infra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pulumi>=3.190.0",
    "pulumi-neon",
]

[tool.uv.sources]
pulumi-neon = { path = "sdks/neon" }
