# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .api_key import *
from .branch import *
from .database import *
from .endpoint import *
from .get_branch_endpoints import *
from .get_branch_role_password import *
from .get_branch_roles import *
from .get_branches import *
from .get_project import *
from .jwks_url import *
from .project import *
from .project_permission import *
from .provider import *
from .role import *
from .vpc_endpoint_assignment import *
from .vpc_endpoint_restriction import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_neon.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_neon.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "neon",
  "mod": "index/apiKey",
  "fqn": "pulumi_neon",
  "classes": {
   "neon:index/apiKey:ApiKey": "ApiKey"
  }
 },
 {
  "pkg": "neon",
  "mod": "index/branch",
  "fqn": "pulumi_neon",
  "classes": {
   "neon:index/branch:Branch": "Branch"
  }
 },
 {
  "pkg": "neon",
  "mod": "index/database",
  "fqn": "pulumi_neon",
  "classes": {
   "neon:index/database:Database": "Database"
  }
 },
 {
  "pkg": "neon",
  "mod": "index/endpoint",
  "fqn": "pulumi_neon",
  "classes": {
   "neon:index/endpoint:Endpoint": "Endpoint"
  }
 },
 {
  "pkg": "neon",
  "mod": "index/jwksUrl",
  "fqn": "pulumi_neon",
  "classes": {
   "neon:index/jwksUrl:JwksUrl": "JwksUrl"
  }
 },
 {
  "pkg": "neon",
  "mod": "index/project",
  "fqn": "pulumi_neon",
  "classes": {
   "neon:index/project:Project": "Project"
  }
 },
 {
  "pkg": "neon",
  "mod": "index/projectPermission",
  "fqn": "pulumi_neon",
  "classes": {
   "neon:index/projectPermission:ProjectPermission": "ProjectPermission"
  }
 },
 {
  "pkg": "neon",
  "mod": "index/role",
  "fqn": "pulumi_neon",
  "classes": {
   "neon:index/role:Role": "Role"
  }
 },
 {
  "pkg": "neon",
  "mod": "index/vpcEndpointAssignment",
  "fqn": "pulumi_neon",
  "classes": {
   "neon:index/vpcEndpointAssignment:VpcEndpointAssignment": "VpcEndpointAssignment"
  }
 },
 {
  "pkg": "neon",
  "mod": "index/vpcEndpointRestriction",
  "fqn": "pulumi_neon",
  "classes": {
   "neon:index/vpcEndpointRestriction:VpcEndpointRestriction": "VpcEndpointRestriction"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "neon",
  "token": "pulumi:providers:neon",
  "fqn": "pulumi_neon",
  "class": "Provider"
 }
]
"""
)
