# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetBranchRolesResult',
    'AwaitableGetBranchRolesResult',
    'get_branch_roles',
    'get_branch_roles_output',
]

@pulumi.output_type
class GetBranchRolesResult:
    """
    A collection of values returned by getBranchRoles.
    """
    def __init__(__self__, branch_id=None, id=None, project_id=None, roles=None):
        if branch_id and not isinstance(branch_id, str):
            raise TypeError("Expected argument 'branch_id' to be a str")
        pulumi.set(__self__, "branch_id", branch_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if project_id and not isinstance(project_id, str):
            raise TypeError("Expected argument 'project_id' to be a str")
        pulumi.set(__self__, "project_id", project_id)
        if roles and not isinstance(roles, list):
            raise TypeError("Expected argument 'roles' to be a list")
        pulumi.set(__self__, "roles", roles)

    @_builtins.property
    @pulumi.getter(name="branchId")
    def branch_id(self) -> _builtins.str:
        return pulumi.get(self, "branch_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> _builtins.str:
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter
    def roles(self) -> Optional[Sequence['outputs.GetBranchRolesRoleResult']]:
        return pulumi.get(self, "roles")


class AwaitableGetBranchRolesResult(GetBranchRolesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetBranchRolesResult(
            branch_id=self.branch_id,
            id=self.id,
            project_id=self.project_id,
            roles=self.roles)


def get_branch_roles(branch_id: Optional[_builtins.str] = None,
                     id: Optional[_builtins.str] = None,
                     project_id: Optional[_builtins.str] = None,
                     roles: Optional[Sequence[Union['GetBranchRolesRoleArgs', 'GetBranchRolesRoleArgsDict']]] = None,
                     opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetBranchRolesResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['branchId'] = branch_id
    __args__['id'] = id
    __args__['projectId'] = project_id
    __args__['roles'] = roles
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('neon:index/getBranchRoles:getBranchRoles', __args__, opts=opts, typ=GetBranchRolesResult, package_ref=_utilities.get_package()).value

    return AwaitableGetBranchRolesResult(
        branch_id=pulumi.get(__ret__, 'branch_id'),
        id=pulumi.get(__ret__, 'id'),
        project_id=pulumi.get(__ret__, 'project_id'),
        roles=pulumi.get(__ret__, 'roles'))
def get_branch_roles_output(branch_id: Optional[pulumi.Input[_builtins.str]] = None,
                            id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            project_id: Optional[pulumi.Input[_builtins.str]] = None,
                            roles: Optional[pulumi.Input[Optional[Sequence[Union['GetBranchRolesRoleArgs', 'GetBranchRolesRoleArgsDict']]]]] = None,
                            opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetBranchRolesResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['branchId'] = branch_id
    __args__['id'] = id
    __args__['projectId'] = project_id
    __args__['roles'] = roles
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('neon:index/getBranchRoles:getBranchRoles', __args__, opts=opts, typ=GetBranchRolesResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetBranchRolesResult(
        branch_id=pulumi.get(__response__, 'branch_id'),
        id=pulumi.get(__response__, 'id'),
        project_id=pulumi.get(__response__, 'project_id'),
        roles=pulumi.get(__response__, 'roles')))
