# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['VpcEndpointRestrictionArgs', 'VpcEndpointRestriction']

@pulumi.input_type
class VpcEndpointRestrictionArgs:
    def __init__(__self__, *,
                 label: pulumi.Input[_builtins.str],
                 project_id: pulumi.Input[_builtins.str],
                 vpc_endpoint_id: pulumi.Input[_builtins.str],
                 vpc_endpoint_restriction_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a VpcEndpointRestriction resource.
        :param pulumi.Input[_builtins.str] label: A descriptive label for the VPC endpoint.
        :param pulumi.Input[_builtins.str] project_id: The Neon project ID.
        :param pulumi.Input[_builtins.str] vpc_endpoint_id: The VPC endpoint ID.
        """
        pulumi.set(__self__, "label", label)
        pulumi.set(__self__, "project_id", project_id)
        pulumi.set(__self__, "vpc_endpoint_id", vpc_endpoint_id)
        if vpc_endpoint_restriction_id is not None:
            pulumi.set(__self__, "vpc_endpoint_restriction_id", vpc_endpoint_restriction_id)

    @_builtins.property
    @pulumi.getter
    def label(self) -> pulumi.Input[_builtins.str]:
        """
        A descriptive label for the VPC endpoint.
        """
        return pulumi.get(self, "label")

    @label.setter
    def label(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "label", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.str]:
        """
        The Neon project ID.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter(name="vpcEndpointId")
    def vpc_endpoint_id(self) -> pulumi.Input[_builtins.str]:
        """
        The VPC endpoint ID.
        """
        return pulumi.get(self, "vpc_endpoint_id")

    @vpc_endpoint_id.setter
    def vpc_endpoint_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "vpc_endpoint_id", value)

    @_builtins.property
    @pulumi.getter(name="vpcEndpointRestrictionId")
    def vpc_endpoint_restriction_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "vpc_endpoint_restriction_id")

    @vpc_endpoint_restriction_id.setter
    def vpc_endpoint_restriction_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "vpc_endpoint_restriction_id", value)


@pulumi.input_type
class _VpcEndpointRestrictionState:
    def __init__(__self__, *,
                 label: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 vpc_endpoint_id: Optional[pulumi.Input[_builtins.str]] = None,
                 vpc_endpoint_restriction_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering VpcEndpointRestriction resources.
        :param pulumi.Input[_builtins.str] label: A descriptive label for the VPC endpoint.
        :param pulumi.Input[_builtins.str] project_id: The Neon project ID.
        :param pulumi.Input[_builtins.str] vpc_endpoint_id: The VPC endpoint ID.
        """
        if label is not None:
            pulumi.set(__self__, "label", label)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)
        if vpc_endpoint_id is not None:
            pulumi.set(__self__, "vpc_endpoint_id", vpc_endpoint_id)
        if vpc_endpoint_restriction_id is not None:
            pulumi.set(__self__, "vpc_endpoint_restriction_id", vpc_endpoint_restriction_id)

    @_builtins.property
    @pulumi.getter
    def label(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A descriptive label for the VPC endpoint.
        """
        return pulumi.get(self, "label")

    @label.setter
    def label(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "label", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The Neon project ID.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter(name="vpcEndpointId")
    def vpc_endpoint_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The VPC endpoint ID.
        """
        return pulumi.get(self, "vpc_endpoint_id")

    @vpc_endpoint_id.setter
    def vpc_endpoint_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "vpc_endpoint_id", value)

    @_builtins.property
    @pulumi.getter(name="vpcEndpointRestrictionId")
    def vpc_endpoint_restriction_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "vpc_endpoint_restriction_id")

    @vpc_endpoint_restriction_id.setter
    def vpc_endpoint_restriction_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "vpc_endpoint_restriction_id", value)


@pulumi.type_token("neon:index/vpcEndpointRestriction:VpcEndpointRestriction")
class VpcEndpointRestriction(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 label: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 vpc_endpoint_id: Optional[pulumi.Input[_builtins.str]] = None,
                 vpc_endpoint_restriction_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a VpcEndpointRestriction resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] label: A descriptive label for the VPC endpoint.
        :param pulumi.Input[_builtins.str] project_id: The Neon project ID.
        :param pulumi.Input[_builtins.str] vpc_endpoint_id: The VPC endpoint ID.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: VpcEndpointRestrictionArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a VpcEndpointRestriction resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param VpcEndpointRestrictionArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(VpcEndpointRestrictionArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 label: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 vpc_endpoint_id: Optional[pulumi.Input[_builtins.str]] = None,
                 vpc_endpoint_restriction_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = VpcEndpointRestrictionArgs.__new__(VpcEndpointRestrictionArgs)

            if label is None and not opts.urn:
                raise TypeError("Missing required property 'label'")
            __props__.__dict__["label"] = label
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
            if vpc_endpoint_id is None and not opts.urn:
                raise TypeError("Missing required property 'vpc_endpoint_id'")
            __props__.__dict__["vpc_endpoint_id"] = vpc_endpoint_id
            __props__.__dict__["vpc_endpoint_restriction_id"] = vpc_endpoint_restriction_id
        super(VpcEndpointRestriction, __self__).__init__(
            'neon:index/vpcEndpointRestriction:VpcEndpointRestriction',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            label: Optional[pulumi.Input[_builtins.str]] = None,
            project_id: Optional[pulumi.Input[_builtins.str]] = None,
            vpc_endpoint_id: Optional[pulumi.Input[_builtins.str]] = None,
            vpc_endpoint_restriction_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'VpcEndpointRestriction':
        """
        Get an existing VpcEndpointRestriction resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] label: A descriptive label for the VPC endpoint.
        :param pulumi.Input[_builtins.str] project_id: The Neon project ID.
        :param pulumi.Input[_builtins.str] vpc_endpoint_id: The VPC endpoint ID.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _VpcEndpointRestrictionState.__new__(_VpcEndpointRestrictionState)

        __props__.__dict__["label"] = label
        __props__.__dict__["project_id"] = project_id
        __props__.__dict__["vpc_endpoint_id"] = vpc_endpoint_id
        __props__.__dict__["vpc_endpoint_restriction_id"] = vpc_endpoint_restriction_id
        return VpcEndpointRestriction(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def label(self) -> pulumi.Output[_builtins.str]:
        """
        A descriptive label for the VPC endpoint.
        """
        return pulumi.get(self, "label")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[_builtins.str]:
        """
        The Neon project ID.
        """
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter(name="vpcEndpointId")
    def vpc_endpoint_id(self) -> pulumi.Output[_builtins.str]:
        """
        The VPC endpoint ID.
        """
        return pulumi.get(self, "vpc_endpoint_id")

    @_builtins.property
    @pulumi.getter(name="vpcEndpointRestrictionId")
    def vpc_endpoint_restriction_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "vpc_endpoint_restriction_id")

